export const countries = [
  {
    name: "Ascension Island",
    emoji: "🇦🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AC.svg",
    code: "AC",
  },
  {
    name: "Andorra",
    emoji: "🇦🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg",
    code: "AD",
  },
  {
    name: "United Arab Emirates",
    emoji: "🇦🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg",
    code: "AE",
  },
  {
    name: "Afghanistan",
    emoji: "🇦🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg",
    code: "AF",
  },
  {
    name: "Antigua & Barbuda",
    emoji: "🇦🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg",
    code: "AG",
  },
  {
    name: "Anguilla",
    emoji: "🇦🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg",
    code: "AI",
  },
  {
    name: "Albania",
    emoji: "🇦🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg",
    code: "AL",
  },
  {
    name: "Armenia",
    emoji: "🇦🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg",
    code: "AM",
  },
  {
    name: "Angola",
    emoji: "🇦🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg",
    code: "AO",
  },
  {
    name: "Antarctica",
    emoji: "🇦🇶",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg",
    code: "AQ",
  },
  {
    name: "Argentina",
    emoji: "🇦🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg",
    code: "AR",
  },
  {
    name: "American Samoa",
    emoji: "🇦🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg",
    code: "AS",
  },
  {
    name: "Austria",
    emoji: "🇦🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg",
    code: "AT",
  },
  {
    name: "Australia",
    emoji: "🇦🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg",
    code: "AU",
  },
  {
    name: "Aruba",
    emoji: "🇦🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg",
    code: "AW",
  },
  {
    name: "Åland Islands",
    emoji: "🇦🇽",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg",
    code: "AX",
  },
  {
    name: "Azerbaijan",
    emoji: "🇦🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg",
    code: "AZ",
  },
  {
    name: "Bosnia & Herzegovina",
    emoji: "🇧🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg",
    code: "BA",
  },
  {
    name: "Barbados",
    emoji: "🇧🇧",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg",
    code: "BB",
  },
  {
    name: "Bangladesh",
    emoji: "🇧🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg",
    code: "BD",
  },
  {
    name: "Belgium",
    emoji: "🇧🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg",
    code: "BE",
  },
  {
    name: "Burkina Faso",
    emoji: "🇧🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg",
    code: "BF",
  },
  {
    name: "Bulgaria",
    emoji: "🇧🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg",
    code: "BG",
  },
  {
    name: "Bahrain",
    emoji: "🇧🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg",
    code: "BH",
  },
  {
    name: "Burundi",
    emoji: "🇧🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg",
    code: "BI",
  },
  {
    name: "Benin",
    emoji: "🇧🇯",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg",
    code: "BJ",
  },
  {
    name: "St. Barthélemy",
    emoji: "🇧🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg",
    code: "BL",
  },
  {
    name: "Bermuda",
    emoji: "🇧🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg",
    code: "BM",
  },
  {
    name: "Brunei",
    emoji: "🇧🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg",
    code: "BN",
  },
  {
    name: "Bolivia",
    emoji: "🇧🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg",
    code: "BO",
  },
  {
    name: "Caribbean Netherlands",
    emoji: "🇧🇶",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg",
    code: "BQ",
  },
  {
    name: "Brazil",
    emoji: "🇧🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
    code: "BR",
  },
  {
    name: "Bahamas",
    emoji: "🇧🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg",
    code: "BS",
  },
  {
    name: "Bhutan",
    emoji: "🇧🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg",
    code: "BT",
  },
  {
    name: "Bouvet Island",
    emoji: "🇧🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BV.svg",
    code: "BV",
  },
  {
    name: "Botswana",
    emoji: "🇧🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg",
    code: "BW",
  },
  {
    name: "Belarus",
    emoji: "🇧🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg",
    code: "BY",
  },
  {
    name: "Belize",
    emoji: "🇧🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg",
    code: "BZ",
  },
  {
    name: "Canada",
    emoji: "🇨🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg",
    code: "CA",
  },
  {
    name: "Cocos (Keeling) Islands",
    emoji: "🇨🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg",
    code: "CC",
  },
  {
    name: "Congo - Kinshasa",
    emoji: "🇨🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg",
    code: "CD",
  },
  {
    name: "Central African Republic",
    emoji: "🇨🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg",
    code: "CF",
  },
  {
    name: "Congo - Brazzaville",
    emoji: "🇨🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg",
    code: "CG",
  },
  {
    name: "Switzerland",
    emoji: "🇨🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg",
    code: "CH",
  },
  {
    name: "Côte d’Ivoire",
    emoji: "🇨🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg",
    code: "CI",
  },
  {
    name: "Cook Islands",
    emoji: "🇨🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg",
    code: "CK",
  },
  {
    name: "Chile",
    emoji: "🇨🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg",
    code: "CL",
  },
  {
    name: "Cameroon",
    emoji: "🇨🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg",
    code: "CM",
  },
  {
    name: "China",
    emoji: "🇨🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg",
    code: "CN",
  },
  {
    name: "Colombia",
    emoji: "🇨🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg",
    code: "CO",
  },
  {
    name: "Clipperton Island",
    emoji: "🇨🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CP.svg",
    code: "CP",
  },
  {
    name: "Costa Rica",
    emoji: "🇨🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg",
    code: "CR",
  },
  {
    name: "Cuba",
    emoji: "🇨🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg",
    code: "CU",
  },
  {
    name: "Cape Verde",
    emoji: "🇨🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg",
    code: "CV",
  },
  {
    name: "Curaçao",
    emoji: "🇨🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg",
    code: "CW",
  },
  {
    name: "Christmas Island",
    emoji: "🇨🇽",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg",
    code: "CX",
  },
  {
    name: "Cyprus",
    emoji: "🇨🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg",
    code: "CY",
  },
  {
    name: "Czechia",
    emoji: "🇨🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg",
    code: "CZ",
  },
  {
    name: "Germany",
    emoji: "🇩🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg",
    code: "DE",
  },
  {
    name: "Diego Garcia",
    emoji: "🇩🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DG.svg",
    code: "DG",
  },
  {
    name: "Djibouti",
    emoji: "🇩🇯",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg",
    code: "DJ",
  },
  {
    name: "Denmark",
    emoji: "🇩🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg",
    code: "DK",
  },
  {
    name: "Dominica",
    emoji: "🇩🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    emoji: "🇩🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg",
    code: "DO",
  },
  {
    name: "Algeria",
    emoji: "🇩🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg",
    code: "DZ",
  },
  {
    name: "Ceuta & Melilla",
    emoji: "🇪🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EA.svg",
    code: "EA",
  },
  {
    name: "Ecuador",
    emoji: "🇪🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg",
    code: "EC",
  },
  {
    name: "Estonia",
    emoji: "🇪🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg",
    code: "EE",
  },
  {
    name: "Egypt",
    emoji: "🇪🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg",
    code: "EG",
  },
  {
    name: "Western Sahara",
    emoji: "🇪🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg",
    code: "EH",
  },
  {
    name: "Eritrea",
    emoji: "🇪🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg",
    code: "ER",
  },
  {
    name: "Spain",
    emoji: "🇪🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg",
    code: "ES",
  },
  {
    name: "Ethiopia",
    emoji: "🇪🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg",
    code: "ET",
  },
  {
    name: "European Union",
    emoji: "🇪🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EU.svg",
    code: "EU",
  },
  {
    name: "Finland",
    emoji: "🇫🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg",
    code: "FI",
  },
  {
    name: "Fiji",
    emoji: "🇫🇯",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg",
    code: "FJ",
  },
  {
    name: "Falkland Islands",
    emoji: "🇫🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg",
    code: "FK",
  },
  {
    name: "Micronesia",
    emoji: "🇫🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg",
    code: "FM",
  },
  {
    name: "Faroe Islands",
    emoji: "🇫🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg",
    code: "FO",
  },
  {
    name: "France",
    emoji: "🇫🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg",
    code: "FR",
  },
  {
    name: "Gabon",
    emoji: "🇬🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg",
    code: "GA",
  },
  {
    name: "United Kingdom",
    emoji: "🇬🇧",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg",
    code: "GB",
  },
  {
    name: "Grenada",
    emoji: "🇬🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg",
    code: "GD",
  },
  {
    name: "Georgia",
    emoji: "🇬🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg",
    code: "GE",
  },
  {
    name: "French Guiana",
    emoji: "🇬🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg",
    code: "GF",
  },
  {
    name: "Guernsey",
    emoji: "🇬🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg",
    code: "GG",
  },
  {
    name: "Ghana",
    emoji: "🇬🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg",
    code: "GH",
  },
  {
    name: "Gibraltar",
    emoji: "🇬🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg",
    code: "GI",
  },
  {
    name: "Greenland",
    emoji: "🇬🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg",
    code: "GL",
  },
  {
    name: "Gambia",
    emoji: "🇬🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg",
    code: "GM",
  },
  {
    name: "Guinea",
    emoji: "🇬🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg",
    code: "GN",
  },
  {
    name: "Guadeloupe",
    emoji: "🇬🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg",
    code: "GP",
  },
  {
    name: "Equatorial Guinea",
    emoji: "🇬🇶",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg",
    code: "GQ",
  },
  {
    name: "Greece",
    emoji: "🇬🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg",
    code: "GR",
  },
  {
    name: "South Georgia & South Sandwich Islands",
    emoji: "🇬🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg",
    code: "GS",
  },
  {
    name: "Guatemala",
    emoji: "🇬🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg",
    code: "GT",
  },
  {
    name: "Guam",
    emoji: "🇬🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg",
    code: "GU",
  },
  {
    name: "Guinea-Bissau",
    emoji: "🇬🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg",
    code: "GW",
  },
  {
    name: "Guyana",
    emoji: "🇬🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg",
    code: "GY",
  },
  {
    name: "Hong Kong SAR China",
    emoji: "🇭🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg",
    code: "HK",
  },
  {
    name: "Heard & McDonald Islands",
    emoji: "🇭🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HM.svg",
    code: "HM",
  },
  {
    name: "Honduras",
    emoji: "🇭🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg",
    code: "HN",
  },
  {
    name: "Croatia",
    emoji: "🇭🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg",
    code: "HR",
  },
  {
    name: "Haiti",
    emoji: "🇭🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg",
    code: "HT",
  },
  {
    name: "Hungary",
    emoji: "🇭🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg",
    code: "HU",
  },
  {
    name: "Canary Islands",
    emoji: "🇮🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IC.svg",
    code: "IC",
  },
  {
    name: "Indonesia",
    emoji: "🇮🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg",
    code: "ID",
  },
  {
    name: "Ireland",
    emoji: "🇮🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg",
    code: "IE",
  },
  {
    name: "Israel",
    emoji: "🇮🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg",
    code: "IL",
  },
  {
    name: "Isle of Man",
    emoji: "🇮🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg",
    code: "IM",
  },
  {
    name: "India",
    emoji: "🇮🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg",
    code: "IN",
  },
  {
    name: "British Indian Ocean Territory",
    emoji: "🇮🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg",
    code: "IO",
  },
  {
    name: "Iraq",
    emoji: "🇮🇶",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg",
    code: "IQ",
  },
  {
    name: "Iran",
    emoji: "🇮🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg",
    code: "IR",
  },
  {
    name: "Iceland",
    emoji: "🇮🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg",
    code: "IS",
  },
  {
    name: "Italy",
    emoji: "🇮🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg",
    code: "IT",
  },
  {
    name: "Jersey",
    emoji: "🇯🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg",
    code: "JE",
  },
  {
    name: "Jamaica",
    emoji: "🇯🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg",
    code: "JM",
  },
  {
    name: "Jordan",
    emoji: "🇯🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg",
    code: "JO",
  },
  {
    name: "Japan",
    emoji: "🇯🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg",
    code: "JP",
  },
  {
    name: "Kenya",
    emoji: "🇰🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg",
    code: "KE",
  },
  {
    name: "Kyrgyzstan",
    emoji: "🇰🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg",
    code: "KG",
  },
  {
    name: "Cambodia",
    emoji: "🇰🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg",
    code: "KH",
  },
  {
    name: "Kiribati",
    emoji: "🇰🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg",
    code: "KI",
  },
  {
    name: "Comoros",
    emoji: "🇰🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg",
    code: "KM",
  },
  {
    name: "St. Kitts & Nevis",
    emoji: "🇰🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg",
    code: "KN",
  },
  {
    name: "North Korea",
    emoji: "🇰🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg",
    code: "KP",
  },
  {
    name: "South Korea",
    emoji: "🇰🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg",
    code: "KR",
  },
  {
    name: "Kuwait",
    emoji: "🇰🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg",
    code: "KW",
  },
  {
    name: "Cayman Islands",
    emoji: "🇰🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg",
    code: "KY",
  },
  {
    name: "Kazakhstan",
    emoji: "🇰🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg",
    code: "KZ",
  },
  {
    name: "Laos",
    emoji: "🇱🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg",
    code: "LA",
  },
  {
    name: "Lebanon",
    emoji: "🇱🇧",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg",
    code: "LB",
  },
  {
    name: "St. Lucia",
    emoji: "🇱🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg",
    code: "LC",
  },
  {
    name: "Liechtenstein",
    emoji: "🇱🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg",
    code: "LI",
  },
  {
    name: "Sri Lanka",
    emoji: "🇱🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg",
    code: "LK",
  },
  {
    name: "Liberia",
    emoji: "🇱🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg",
    code: "LR",
  },
  {
    name: "Lesotho",
    emoji: "🇱🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg",
    code: "LS",
  },
  {
    name: "Lithuania",
    emoji: "🇱🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg",
    code: "LT",
  },
  {
    name: "Luxembourg",
    emoji: "🇱🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg",
    code: "LU",
  },
  {
    name: "Latvia",
    emoji: "🇱🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg",
    code: "LV",
  },
  {
    name: "Libya",
    emoji: "🇱🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg",
    code: "LY",
  },
  {
    name: "Morocco",
    emoji: "🇲🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg",
    code: "MA",
  },
  {
    name: "Monaco",
    emoji: "🇲🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg",
    code: "MC",
  },
  {
    name: "Moldova",
    emoji: "🇲🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg",
    code: "MD",
  },
  {
    name: "Montenegro",
    emoji: "🇲🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg",
    code: "ME",
  },
  {
    name: "St. Martin",
    emoji: "🇲🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MF.svg",
    code: "MF",
  },
  {
    name: "Madagascar",
    emoji: "🇲🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg",
    code: "MG",
  },
  {
    name: "Marshall Islands",
    emoji: "🇲🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg",
    code: "MH",
  },
  {
    name: "North Macedonia",
    emoji: "🇲🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg",
    code: "MK",
  },
  {
    name: "Mali",
    emoji: "🇲🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg",
    code: "ML",
  },
  {
    name: "Myanmar (Burma)",
    emoji: "🇲🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg",
    code: "MM",
  },
  {
    name: "Mongolia",
    emoji: "🇲🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg",
    code: "MN",
  },
  {
    name: "Macao SAR China",
    emoji: "🇲🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg",
    code: "MO",
  },
  {
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg",
    code: "MP",
  },
  {
    name: "Martinique",
    emoji: "🇲🇶",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg",
    code: "MQ",
  },
  {
    name: "Mauritania",
    emoji: "🇲🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg",
    code: "MR",
  },
  {
    name: "Montserrat",
    emoji: "🇲🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg",
    code: "MS",
  },
  {
    name: "Malta",
    emoji: "🇲🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg",
    code: "MT",
  },
  {
    name: "Mauritius",
    emoji: "🇲🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg",
    code: "MU",
  },
  {
    name: "Maldives",
    emoji: "🇲🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg",
    code: "MV",
  },
  {
    name: "Malawi",
    emoji: "🇲🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg",
    code: "MW",
  },
  {
    name: "Mexico",
    emoji: "🇲🇽",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg",
    code: "MX",
  },
  {
    name: "Malaysia",
    emoji: "🇲🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg",
    code: "MY",
  },
  {
    name: "Mozambique",
    emoji: "🇲🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg",
    code: "MZ",
  },
  {
    name: "Namibia",
    emoji: "🇳🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg",
    code: "NA",
  },
  {
    name: "New Caledonia",
    emoji: "🇳🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg",
    code: "NC",
  },
  {
    name: "Niger",
    emoji: "🇳🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg",
    code: "NE",
  },
  {
    name: "Norfolk Island",
    emoji: "🇳🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg",
    code: "NF",
  },
  {
    name: "Nigeria",
    emoji: "🇳🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg",
    code: "NG",
  },
  {
    name: "Nicaragua",
    emoji: "🇳🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg",
    code: "NI",
  },
  {
    name: "Netherlands",
    emoji: "🇳🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg",
    code: "NL",
  },
  {
    name: "Norway",
    emoji: "🇳🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg",
    code: "NO",
  },
  {
    name: "Nepal",
    emoji: "🇳🇵",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg",
    code: "NP",
  },
  {
    name: "Nauru",
    emoji: "🇳🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg",
    code: "NR",
  },
  {
    name: "Niue",
    emoji: "🇳🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg",
    code: "NU",
  },
  {
    name: "New Zealand",
    emoji: "🇳🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg",
    code: "NZ",
  },
  {
    name: "Oman",
    emoji: "🇴🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg",
    code: "OM",
  },
  {
    name: "Panama",
    emoji: "🇵🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg",
    code: "PA",
  },
  {
    name: "Peru",
    emoji: "🇵🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg",
    code: "PE",
  },
  {
    name: "French Polynesia",
    emoji: "🇵🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg",
    code: "PF",
  },
  {
    name: "Papua New Guinea",
    emoji: "🇵🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg",
    code: "PG",
  },
  {
    name: "Philippines",
    emoji: "🇵🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg",
    code: "PH",
  },
  {
    name: "Pakistan",
    emoji: "🇵🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg",
    code: "PK",
  },
  {
    name: "Poland",
    emoji: "🇵🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg",
    code: "PL",
  },
  {
    name: "St. Pierre & Miquelon",
    emoji: "🇵🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg",
    code: "PM",
  },
  {
    name: "Pitcairn Islands",
    emoji: "🇵🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg",
    code: "PN",
  },
  {
    name: "Puerto Rico",
    emoji: "🇵🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg",
    code: "PR",
  },
  {
    name: "Palestinian Territories",
    emoji: "🇵🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg",
    code: "PS",
  },
  {
    name: "Portugal",
    emoji: "🇵🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg",
    code: "PT",
  },
  {
    name: "Palau",
    emoji: "🇵🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg",
    code: "PW",
  },
  {
    name: "Paraguay",
    emoji: "🇵🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg",
    code: "PY",
  },
  {
    name: "Qatar",
    emoji: "🇶🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg",
    code: "QA",
  },
  {
    name: "Réunion",
    emoji: "🇷🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg",
    code: "RE",
  },
  {
    name: "Romania",
    emoji: "🇷🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg",
    code: "RO",
  },
  {
    name: "Serbia",
    emoji: "🇷🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg",
    code: "RS",
  },
  {
    name: "Russia",
    emoji: "🇷🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg",
    code: "RU",
  },
  {
    name: "Rwanda",
    emoji: "🇷🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg",
    code: "RW",
  },
  {
    name: "Saudi Arabia",
    emoji: "🇸🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg",
    code: "SA",
  },
  {
    name: "Solomon Islands",
    emoji: "🇸🇧",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg",
    code: "SB",
  },
  {
    name: "Seychelles",
    emoji: "🇸🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg",
    code: "SC",
  },
  {
    name: "Sudan",
    emoji: "🇸🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg",
    code: "SD",
  },
  {
    name: "Sweden",
    emoji: "🇸🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg",
    code: "SE",
  },
  {
    name: "Singapore",
    emoji: "🇸🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg",
    code: "SG",
  },
  {
    name: "St. Helena",
    emoji: "🇸🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg",
    code: "SH",
  },
  {
    name: "Slovenia",
    emoji: "🇸🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg",
    code: "SI",
  },
  {
    name: "Svalbard & Jan Mayen",
    emoji: "🇸🇯",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg",
    code: "SJ",
  },
  {
    name: "Slovakia",
    emoji: "🇸🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg",
    code: "SK",
  },
  {
    name: "Sierra Leone",
    emoji: "🇸🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg",
    code: "SL",
  },
  {
    name: "San Marino",
    emoji: "🇸🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg",
    code: "SM",
  },
  {
    name: "Senegal",
    emoji: "🇸🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg",
    code: "SN",
  },
  {
    name: "Somalia",
    emoji: "🇸🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg",
    code: "SO",
  },
  {
    name: "Suriname",
    emoji: "🇸🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg",
    code: "SR",
  },
  {
    name: "South Sudan",
    emoji: "🇸🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg",
    code: "SS",
  },
  {
    name: "São Tomé & Príncipe",
    emoji: "🇸🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg",
    code: "ST",
  },
  {
    name: "El Salvador",
    emoji: "🇸🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg",
    code: "SV",
  },
  {
    name: "Sint Maarten",
    emoji: "🇸🇽",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg",
    code: "SX",
  },
  {
    name: "Syria",
    emoji: "🇸🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg",
    code: "SY",
  },
  {
    name: "Eswatini",
    emoji: "🇸🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg",
    code: "SZ",
  },
  {
    name: "Tristan da Cunha",
    emoji: "🇹🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TA.svg",
    code: "TA",
  },
  {
    name: "Turks & Caicos Islands",
    emoji: "🇹🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg",
    code: "TC",
  },
  {
    name: "Chad",
    emoji: "🇹🇩",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg",
    code: "TD",
  },
  {
    name: "French Southern Territories",
    emoji: "🇹🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg",
    code: "TF",
  },
  {
    name: "Togo",
    emoji: "🇹🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg",
    code: "TG",
  },
  {
    name: "Thailand",
    emoji: "🇹🇭",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg",
    code: "TH",
  },
  {
    name: "Tajikistan",
    emoji: "🇹🇯",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg",
    code: "TJ",
  },
  {
    name: "Tokelau",
    emoji: "🇹🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg",
    code: "TK",
  },
  {
    name: "Timor-Leste",
    emoji: "🇹🇱",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg",
    code: "TL",
  },
  {
    name: "Turkmenistan",
    emoji: "🇹🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg",
    code: "TM",
  },
  {
    name: "Tunisia",
    emoji: "🇹🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg",
    code: "TN",
  },
  {
    name: "Tonga",
    emoji: "🇹🇴",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg",
    code: "TO",
  },
  {
    name: "Turkey",
    emoji: "🇹🇷",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg",
    code: "TR",
  },
  {
    name: "Trinidad & Tobago",
    emoji: "🇹🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg",
    code: "TT",
  },
  {
    name: "Tuvalu",
    emoji: "🇹🇻",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg",
    code: "TV",
  },
  {
    name: "Taiwan",
    emoji: "🇹🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg",
    code: "TW",
  },
  {
    name: "Tanzania",
    emoji: "🇹🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg",
    code: "TZ",
  },
  {
    name: "Ukraine",
    emoji: "🇺🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg",
    code: "UA",
  },
  {
    name: "Uganda",
    emoji: "🇺🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg",
    code: "UG",
  },
  {
    name: "U.S. Outlying Islands",
    emoji: "🇺🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UM.svg",
    code: "UM",
  },
  {
    name: "United Nations",
    emoji: "🇺🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UN.svg",
    code: "UN",
  },
  {
    name: "United States",
    emoji: "🇺🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
    code: "US",
  },
  {
    name: "Uruguay",
    emoji: "🇺🇾",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    emoji: "🇺🇿",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg",
    code: "UZ",
  },
  {
    name: "Vatican City",
    emoji: "🇻🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg",
    code: "VA",
  },
  {
    name: "St. Vincent & Grenadines",
    emoji: "🇻🇨",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg",
    code: "VC",
  },
  {
    name: "Venezuela",
    emoji: "🇻🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg",
    code: "VE",
  },
  {
    name: "British Virgin Islands",
    emoji: "🇻🇬",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg",
    code: "VG",
  },
  {
    name: "U.S. Virgin Islands",
    emoji: "🇻🇮",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg",
    code: "VI",
  },
  {
    name: "Vietnam",
    emoji: "🇻🇳",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg",
    code: "VN",
  },
  {
    name: "Vanuatu",
    emoji: "🇻🇺",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg",
    code: "VU",
  },
  {
    name: "Wallis & Futuna",
    emoji: "🇼🇫",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg",
    code: "WF",
  },
  {
    name: "Samoa",
    emoji: "🇼🇸",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg",
    code: "WS",
  },
  {
    name: "Kosovo",
    emoji: "🇽🇰",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/XK.svg",
    code: "XK",
  },
  {
    name: "Yemen",
    emoji: "🇾🇪",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg",
    code: "YE",
  },
  {
    name: "Mayotte",
    emoji: "🇾🇹",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg",
    code: "YT",
  },
  {
    name: "South Africa",
    emoji: "🇿🇦",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg",
    code: "ZA",
  },
  {
    name: "Zambia",
    emoji: "🇿🇲",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    emoji: "🇿🇼",
    image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg",
    code: "ZW",
  },
] as const;
